version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options
