version: '2'

services:
    jetty:
        image: bhuisgen/alpine-jetty
        ports:
            - "8080:8080"
        #environment:
            #- CONSUL_AGENT=consul          # consul agent hostname/IP
            #- CONSUL_SERVICENAME=jetty     # consul service name
            #- CONSUL_SERVICETAGS=dev       # consul service tag
            #- CONSUL_SERVICEPORT=8080      # consul service port
