version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    build:
        depends_on:
            - consul
        image: bhuisgen/alpine-build-make
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - CONSUL_AGENT=consul                                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                                         # consul agent port
            #- CONSUL_KEYPREFIX=/my/path                                # consul key prefix path
            #- BUILD_SCRIPT=/usr/local/build/run.sh                     # build script
            #- BUILD_TIMEOUT=3600                                       # build timeout
            - GIT_URL=git@git.my.domain:mydomain/project.git            # git repository URL
            - GIT_REF=HEAD                                              # git tag/commit reference
            #- PROJECT_SUBDIR=                                          # project subdirectory (leave empty for project root)
            #- CONFIGURE=1                                              # enable configure script (executed only if found)
            #- CONFIGURE_OPTIONS=                                       # configure options
            #- MAKE_OPTIONS=                                            # make options
            #- MAKE_TARGET=                                             # make target (leave empty for default target)
            #- MAKE_TARGETOPTIONS=                                      # make target options
            #- MAKE_INSTALL=1                                           # enable make install
            #- MAKE_INSTALLOPTIONS=                                     # make install options
