version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    registry:
        depends_on:
            - consul
        image: bhuisgen/alpine-registry
        ports:
            - "5000:5000"
        environment:
            - CONSUL_AGENT=consul           # consul agent hostname/IP
            #- CONSUL_PORT=8500             # consul agent port
            - CONSUL_SERVICENAME=registry   # consul service name
            - CONSUL_SERVICETAGS=dev        # consul service tag
            - CONSUL_SERVICEPORT=5000       # consul service port
            #- CONSUL_KEYPREFIX=/my/path    # consul key prefix path
