version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    haproxy:
        depends_on:
            - consul
        image: bhuisgen/alpine-haproxy
        ports:
            - "80:80"
        environment:
            - CONSUL_AGENT=consul                      # consul agent hostname/IP
            #- CONSUL_PORT=8500                        # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix            # consul key prefix path
            - CONSUL_SERVICENAME=haproxy               # consul service name
            - CONSUL_SERVICETAGS=dev                   # consul service tag
            - CONSUL_SERVICEPORT=80                    # consul service port
            - HAPROXY_TEMPLATE=backend                 # configuration template
            - HAPROXY_TEMPLATE_SERVICENAME=myservice   # consul service name
            - HAPROXY_TEMPLATE_SERVICETAG=dev          # consul service tag
            - HAPROXY_TEMPLATE_STATSUSERNAME=haproxy   # haproxy stats user
            - HAPROXY_TEMPLATE_STATSPASSWORD=haproxy   # haproxy stats password
