version: '2'

services:
    dynamodb:
        image: bhuisgen/alpine-dynamodb
        ports:
            - "8000:8000"
        #environment:
            #- CONSUL_AGENT=consul          # consul agent hostname/IP
            #- CONSUL_SERVICENAME=dynamodb  # consul service name
            #- CONSUL_SERVICETAGS=dev       # consul service tag
            #- CONSUL_SERVICEPORT=8000      # consul service port
