version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    dynamodb:
        depends_on:
            - consul
        image: bhuisgen/alpine-dynamodb
        ports:
            - "8000:8000"
        #volumes:
            #- /host/data:/var/lib/dynamodb # volume for data
        environment:
            - CONSUL_AGENT=consul           # consul agent hostname/IP
            #- CONSUL_PORT=8500             # consul agent port
            - CONSUL_SERVICENAME=dynamodb   # consul service name
            - CONSUL_SERVICETAGS=dev        # consul service tag
            - CONSUL_SERVICEPORT=8000       # consul service port
            #- CONSUL_KEYPREFIX=/my/path    # consul key prefix path
