version: '2'

services:
    foo:
        build: .
        environment:
            #- CONTAINER_IP_RESOLVER=route                  # container internal IP resolution mode (route/interface, default: route)
            #- CONTAINER_IP_RESOLVER_INTERFACE_TYPE=inet    # interface type for IP resolution (inet/inet6, default: inet)
            #- CONTAINER_IP_RESOLVER_INTERFACE_NAME=eth0    # interface name for IP resolution (default: eth0)
