version: '2'

services:
    redis:
        image: bhuisgen/alpine-redis
        ports:
            - "6379:6379"
        #environment:
            #- CONSUL_AGENT=consul          # consul agent hostname/IP
            #- CONSUL_SERVICENAME=redis     # consul service name
            #- CONSUL_SERVICETAGS=dev       # consul service tag
            #- CONSUL_SERVICEPORT=6379      # consul service port
